<?php
// Automatically Generated by TestLink Installer - Fri, 13 Sep 24 12:09:39 +0300
define('DB_TYPE', 'mysql');
define('DB_USER', 'user');
define('DB_PASS', 'user');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
